Packer base
Otus-DevOps-2017-11/iPrior_infra pull request #3
Opened 2018-01-06 18:34 UTC by iPrior

2018-01-15 17:48 UTC, Nklya requested changes
Добрый вечер.

Иван, в принципе базовое задание сделано неплохо.

Нужно:
1. Все переменные, которые ты задаешь в variables.example.json, должны быть указаны в секции variables шаблонов пакера https://www.packer.io/docs/templates/user-variables.html 
Это позволит задавать значения по умолчанию и не пихать все в variables.json
2. Разберись со своим редактором. Почему ридми изменилось почти полностью, хотя содержимое не менялось? У тебя переносы разные. Исправь, чтобы дифф был нормальный.

Ну и по поводу доп. задания. В этом доп. задании подразумевалось реализовать старт приложения через системд юнит. Пример есть в следующем дз.

2018-01-15 17:48 UTC, Nklya commented on packer/ubuntu16.json
> +}
Настрой свой редактор, чтобы он добавлял пустую строку при сохранении.
Из-за ее отсутсвия могут быть косяки и странные дифы

2018-01-15 17:48 UTC, Nklya commented on packer/scripts/create-reddit-vm.sh
> +    --metadata startup-script='#!/usr/bin/env bash
Это хак.
В этом доп. задании подразумевалось реализовать старт приложения через системд юнит. Пример есть в следующем дз.

2018-01-15 17:48 UTC, Nklya commented on packer/ubuntu16.json
> +{
Все переменные, которые ты задаешь в variables.example.json, должны быть указаны в секции variables https://www.packer.io/docs/templates/user-variables.html 
Это позволит задавать значения по умолчанию и не пихать все в variables.json

2018-01-15 17:48 UTC, Nklya commented on packer/immutable.json
> +{
Все переменные, которые ты задаешь в variables.example.json, должны быть указаны в секции variables https://www.packer.io/docs/templates/user-variables.html 
Это позволит задавать значения по умолчанию и не пихать все в variables.json

2018-01-21 11:04 UTC, iPrior commented
Доброго дня

> Все переменные, которые ты задаешь в variables.example.json, должны быть указаны в секции variables шаблонов пакера https://www.packer.io/docs/templates/user-variables.html
> Это позволит задавать значения по умолчанию и не пихать все в variables.json

Добавил секцию variables в файлы _ubuntu16.json_ и _immutable.json_


> Разберись со своим редактором. Почему ридми изменилось почти полностью, хотя содержимое не менялось? У тебя переносы разные. Исправь, чтобы дифф был нормальный.

Да, как раз из-за того что "разобрался" дифф и полетел - я отключил в гите _autocrlf_

> Ну и по поводу доп. задания. В этом доп. задании подразумевалось реализовать старт приложения через системд юнит. Пример есть в следующем дз.

У меня была мысль что надо бы через _systemd_ запускать, но почему-то подумал, что в задании было бы тогда явно указан этот момент.

Собсно сделал через _systemd_

> Настрой свой редактор, чтобы он добавлял пустую строку при сохранении.

Да, спасибо, давно надо было это сделать _(найти где это делается)_ но что-то всегда "потом" =)

2018-01-21 12:12 UTC, Nklya approved these changes
Добрый день.
Хоть сегодня и выходной, в качестве исключения сделал ревью.

Все в принципе неплохо, PR апрувлю, замечания ниже.

2018-01-21 12:12 UTC, Nklya commented on packer/ubuntu16.json
> +    "source_image_family": "ubuntu-1604-lts",
source_image_family тоже должен быть обязательный.

2018-01-21 12:12 UTC, Nklya commented on packer/variables.json.example
> +  "disk_size": "10",
Если переменные уже есть в шаблоне пакера и ты их не собираешься переопределять, зачем они здесь указаны?

Вот эти:
+    "machine_type": "f1-micro",
 +    "disk_size": "10",
 +    "disk_type": "pd-standard",
 +    "network": "default"

2018-01-21 12:12 UTC, Nklya commented on packer/.gitignore
> +variables.json
Лучше вынести .gitignore в корень репы

2018-01-21 12:12 UTC, Nklya commented on packer/immutable.json
> +    "source_image_family": "ubuntu-1604-lts",
source_image_family тоже должен быть обязательный.

2018-01-21 12:12 UTC, Nklya commented on packer/scripts/puma_service.sh
> +wget https://gist.githubusercontent.com/Nklya/5db89c8ae4613fe1609fe87f2cdb0203/raw/7dccf8a0f1352dd865f955706085993a203f6ae7/puma.service -O /tmp/puma.service
А можно было просто в папку пакера добавить puma.service и не лепить такие костыли.

2018-01-21 12:12 UTC, Nklya commented on packer/immutable.json
> +      "execute_command": "sudo su - appuser -c \"{{.Path}}\""
Можно было просто в скрипте сделать chown после клонирования репы.

2018-01-21 14:55 UTC, iPrior commented on packer/immutable.json
> +    "source_image_family": "ubuntu-1604-lts",
Простите, но у меня вот тут немного не укладывается в голове, при чем изначально, относительно этой переменной.

У нас все баш скрипты юзают apt-get - как можно давать на откуп "конечному потребителю" указывать операционную систему, ведь он может указать и red-hat например?

Тут получается либо в шел скриптах надо разруливать ситуацию с операционной системой (_может просматривать доступные менеджеры пакетов_), либо, хоть это и условно, не давать указывать операционную систему.

2018-01-21 14:57 UTC, iPrior commented on packer/immutable.json
> +      "execute_command": "sudo su - appuser -c \"{{.Path}}\""
Тут я засомневался относительно `bundle install` - можно ли его от рута запускать..? 
Я с ruby не знаком, от слова "совсем" поэтому сужу по php и его composser, который нельзя запускать от рута.

2018-01-21 14:59 UTC, iPrior commented on packer/scripts/puma_service.sh
> +wget https://gist.githubusercontent.com/Nklya/5db89c8ae4613fe1609fe87f2cdb0203/raw/7dccf8a0f1352dd865f955706085993a203f6ae7/puma.service -O /tmp/puma.service
Согласен, но ооочень хочется поюзать побольше утилит GNU =)

2018-01-21 15:01 UTC, iPrior commented on packer/variables.json.example
> +  "disk_size": "10",
Пожалуй я пересмотрю лекцию и презентацию, а то, сдаётся мне, я не понимаю сакрального смысла этих переменных.

2018-01-21 15:10 UTC, merged

2018-01-22 06:59 UTC, Nklya commented on packer/immutable.json
> +      "execute_command": "sudo su - appuser -c \"{{.Path}}\""
Да, бандл от рута не очень ок.