Terraform 2
Otus-DevOps-2017-11/iPrior_infra pull request #5
Opened 2018-01-23 16:53 UTC by iPrior

Сделал два окружения, *prod* и *stage*

Оба окружения используют модули *vpc*, *app* и *db*

В модули *app* и *db* добавил параметр *instance_name* - он участвует в генерации имени инстанца, тегов и т.д.

В модуле *db* добавил дополнительный параметр, *app_instance_name*, который используется для создания правила firewall -a _(что бы приложение имело доступ к базе данных)_

P.S. readme.md вроде поправил, дикого диффа больше не должно быть.

P.S.2 старые файлы terraform не удалял, а переименовал _(расширение .old)_

2018-01-24 12:03 UTC, Nklya requested changes
Добрый день.

Иван, почти все относительно нормально.

Но:
1. Не выполнено задание на 61-62 слайде.
2. terraform.tfvars.example должен быть в каждом окружении.
3. Если тебе сильно хочется сохранить старые тераформ файлы в папке terraform, сделай terraform/old и скинь их туда. Зачем держать кучу мусора?

И зачем отдельный .gitignore в папке тераформа, если уже есть в корне?

2018-01-24 12:03 UTC, Nklya commented on terraform/app.tf.old
> +resource "google_compute_instance" "app" {
И зачем их сохранять?

2018-01-25 22:59 UTC, iPrior commented
Николай, прошу простить, действительно как то... не заметил что ли, задания на слайдах 61-62.
Даже вот сам не могу понять как такое получилось.

Файлы перенес в директорию old, что бы не мешали

Выполнил задание со слайдов 61-62, правда с указанной конфигурации в PDF гуугл ругался, что имена "вёдер" уже существуют - пришлось изменить имена, о чем я написал в `readme.md`

Относительно файла `.gitignore` в каждой директории - мне кажется так понятней, удобней что ли.
Как было вами выше замечено, не сваливать всё в кучу.

В директории `terraform` лежит `.gitignore` который относится к файлам terraform.

В директории `packer` лежит... и т.д.

Наверное это очередной мой "бзик" как и запись в шел скриптах - `exit 0`

Прошу понять и простить :)

2018-01-26 09:38 UTC, Nklya approved these changes
Да, теперь все ок.

По поводу .gitignore ок, понял твою мысль.

2018-01-26 11:06 UTC, merged